#!/bin/bash
#
# Copyright 2012 NAMD-EMAP-FGV
#
# This file is part of PyPLN. You can get more information at: http://pypln.org/.
#
# PyPLN is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PyPLN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PyPLN.  If not, see <http://www.gnu.org/licenses/>.

# This is a suggested postactivate script. Copy this to (or source it
# from) $VIRTUAL_ENV and it will add some helper functions to your
# environment when the virtualenv is activated

export PYPLN_ROOT=$(dirname $(find "$VIRTUAL_ENV" -type d -name '.git'))

function manage_with_settings() {
	 SETTINGS=$1
	 shift
	 PYTHONPATH="$PYPLN_ROOT:$PYTHONPATH" "$PYPLN_ROOT"/pypln/web/manage.py $* --settings=settings.$SETTINGS;
}

alias manage="manage_with_settings development"
alias test_manage="manage_with_settings test"
