#!/bin/bash
#
# Copyright 2012 NAMD-EMAP-FGV
#
# This file is part of PyPLN. You can get more information at: http://pypln.org/.
#
# PyPLN is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PyPLN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PyPLN.  If not, see <http://www.gnu.org/licenses/>.

# This is a suggested postactivate script. Copy this to (or source it
# from) $VIRTUAL_ENV and it will add some helper functions to your
# environment when the virtualenv is activated

export PYPLN_ROOT=$(dirname $(find -L "$VIRTUAL_ENV" -type d -name '.git') | sort | head -n1)

function manage_with_settings() {
	 SETTINGS=$1
	 shift
	 PYTHONPATH="$PYPLN_ROOT:$PYTHONPATH" python "$PYPLN_ROOT"/manage.py $* --settings=pypln.web.settings.$SETTINGS;
}

function manage() {
	 PYTHONPATH="$PYPLN_ROOT:$PYTHONPATH" python "$PYPLN_ROOT"/manage.py $*
}

alias manage_dev="manage_with_settings development"
alias manage_test="manage_with_settings test"
alias run_tests="manage_test test pypln.web.core.tests"

function reset_development_database() {
	rm "$PYPLN_ROOT"/pypln/web/dev.db
	manage_dev syncdb --noinput
	manage_dev loaddata users corpora documents
	PYTHONPATH="$PYPLN_ROOT:$PYTHONPATH" DJANGO_SETTINGS_MODULE="pypln.web.settings.development" python "$PYPLN_ROOT"/contrib/reset_gridfs_collection.py
}
