# coding: utf-8
#
# Copyright 2012 NAMD-EMAP-FGV
#
# This file is part of PyPLN. You can get more information at: http://pypln.org/.
#
# PyPLN is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PyPLN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PyPLN.  If not, see <http://www.gnu.org/licenses/>.

from django.utils.translation import ugettext as _


TAGSET_EN_NLTK = {
        '$': {'color': '#00CC33',
              'label': _(u'Dollar'),
              'slug': 'dollar'},
        "''": {'color': '#000066',
               'label': _(u'Closing quotation mark'),
               'slug': 'closing-quotation-mark'},
        '(': {'color': '#0099FF',
              'label': _(u'Opening parenthesis'),
              'slug': 'opening-parenthesis'},
        ')': {'color': '#FFFF66',
              'label': _(u'Closing parenthesis'),
              'slug': 'closing-parenthesis'},
        ',': {'color': '#009999',
              'label': _(u'Comma'),
              'slug': 'comma'},
        '.': {'color': '#00AAAA',
              'label': _(u'Dot'),
              'slug': 'dot'},
        '-LRB-': {'color': '#0099FF',
                  'label': _(u'Opening parenthesis'),
                  'slug': 'opening-parenthesis'},
        '-RRB-': {'color': '#FFFF66',
                  'label': _(u'Closing parenthesis'),
                  'slug': 'closing-parenthesis'},
        '--': {'color': '#003333',
               'label': _(u'Dash'),
               'slug': 'dash'},
        '0': {'color': '#009966',
              'label': _(u'Sentence terminator'),
              'slug': 'sentence-terminator'},
        ':': {'color': '#0066CC',
              'label': _(u'Colon or ellipsis'),
              'slug': 'colon-or-ellipsis'},
        'CC': {'color': '#0033FF',
              'label': _(u'Conjunction, coordinating'),
              'slug': 'conjunction-coordinating'},
        'CD': {'color': '#003399',
               'label': _(u'Numeral, cardinal'),
               'slug': 'numeral-cardinal'},
        'DT': {'color': '#000033',
               'label': _(u'Determiner'),
               'slug': 'determiner'},
        'EX': {'color': '#FF9900',
               'label': _(u'Existential there'),
               'slug': 'existential-there'},
        'FW': {'color': '#00FF99',
               'label': _(u'Foreign word'),
               'slug': 'foreign-word'},
        'IN': {'color': '#FF6666',
               'label': _(u'Preposition or conjunction, subordinating'),
               'slug': 'preposition-or-conjunction-subordinating'},
        'JJ': {'color': '#00CCFF',
               'label': _(u'Adjective or numeral, ordinal'),
               'slug': 'adjective-or-numeral-ordinal'},
        'JJR': {'color': '#0000FF',
                'label': _(u'Adjective, comparative'),
                'slug': 'adjective-comparative'},
        'JJS': {'color': '#003300',
                'label': _(u'Adjective, superlative'),
                'slug': 'adjective-superlative'},
        'LS': {'color': '#FFCC66',
               'label': _(u'List item marker'),
               'slug': 'list-item-marker'},
        'MD': {'color': '#FF6633',
               'label': _(u'Modal auxiliary'),
               'slug': 'modal-auxiliary'},
        'NN': {'color': '#00CC00',
               'label': _(u'Noun, common, singular or mass'),
               'slug': 'noun-common-singular-or-mass'},
        'NNP': {'color': '#006666',
                'label': _(u'Noun, proper, singular'),
                'slug': 'noun-proper-singular'},
        'NNPS': {'color': '#FF6600',
                 'label': _(u'Noun, proper, plural'),
                 'slug': 'noun-proper-plural'},
        'NNS': {'color': '#006699',
                'label': _(u'Noun, common, plural'),
                'slug': 'noun-common-plural'},
        'NP': {'color': '#0066FF',
                'label': _(u'Noun, proper, singular'),
                'slug': 'noun-proper-singular'},
        'NPS': {'color': '#000099',
                'label': _(u'Noun, proper, plural'),
                'slug': 'noun-proper-plural'},
        'PDT': {'color': '#0033CC',
                'label': _(u'Pre-determiner'),
                'slug': 'pre-determiner'},
        'POS': {'color': '#FFFF33',
                'label': _(u'Genitive marker'),
                'slug': 'genitive-marker'},
        'PP': {'color': '#000000',
                'label': _(u'Pronoun, personal'),
                'slug': 'pronoun-personal'},
        'PP$': {'color': '#FFCC00',
                'label': _(u'Pronoun, possessive'),
                'slug': 'pronoun-possessive'},
        'PRP': {'color': '#009933',
                'label': _(u'Pronoun, personal'),
                'slug': 'pronoun-personal'},
        'PRP$': {'color': '#00FFFF',
                 'label': _(u'Pronoun, possessive'),
                 'slug': 'pronoun-possessive'},
        'RB': {'color': '#009900',
               'label': _(u'Adverb'),
               'slug': 'adverb'},
        'RBR': {'color': '#FF9933',
                'label': _(u'Adverb, comparative'),
                'slug': 'adverb-comparative'},
        'RBS': {'color': '#FF9966',
                'label': _(u'Adverb, superlative'),
                'slug': 'adverb-superlative'},
        'RP': {'color': '#00CC66',
               'label': _(u'Particle'),
               'slug': 'particle'},
        'SYM': {'color': '#0000CC',
                'label': _(u'Symbol'),
                'slug': 'symbol'},
        'TO': {'color': '#FFFF00',
               'label': _(u'"to" as preposition or infinitive marker'),
               'slug': 'to-as-preposition-or-infinitive-marker'},
        'UH': {'color': '#FF3366',
               'label': _(u'Interjection'),
               'slug': 'interjection'},
        'VB': {'color': '#FFCC33',
               'label': _(u'Verb, base form'),
               'slug': 'verb-base-form'},
        'VBD': {'color': '#0099CC',
                'label': _(u'Verb, past tense'),
                'slug': 'verb-past-tense'},
        'VBG': {'color': '#00FFCC',
                'label': _(u'Verb, present participle or gerund'),
                'slug': 'verb-present-participle-or-gerund'},
        'VBN': {'color': '#00FF66',
                'label': _(u'Verb, past participle'),
                'slug': 'verb-past-participle'},
        'VBP': {'color': '#00FF33',
                'label': _(u'Verb, present tense, not 3rd person singular'),
                'slug': 'verb-present-tense-not-3rd-person-singular'},
        'VBZ': {'color': '#00CC99',
                'label': _(u'Verb, present tense, 3rd person singular'),
                'slug': 'verb-present-tense-3rd-person-singular'},
        'WDT': {'color': '#00FF00',
                'label': _(u'Wh-determiner'),
                'slug': 'wh-determiner'},
        'WP': {'color': '#00CCCC',
               'label': _(u'Wh-pronoun'),
               'slug': 'wh-pronoun'},
        'WP$': {'color': '#003366',
                'label': _(u'Wh-pronoun, possessive'),
                'slug': 'wh-pronoun-possessive'},
        'WRB': {'color': '#006600',
                'label': _(u'Wh-adverb'),
                'slug': 'wh-adverb'},
        '``': {'color': '#006633',
               'label': _(u'Opening quotation mark'),
               'slug': 'opening-quotation-mark'},
        '#': {'color': '#CCCCCC',
              'label': _('Hash'),
              'slug': 'hash'},
        '-NONE-': {'color': '#DDDDDD',
                   'label': 'None',
                   'slug': 'none'},
}

TAGSET_PT_PALAVRAS = {
        'N': {'color': '#00CC00',
              'label': _(u'Noun'),
              'slug': 'noun'},
        'PROP': {'color': '#006666',
                 'label': _(u'Proper Noun'),
                 'slug': 'proper-noun'},
        'SPEC': {'color': '#330033',
                 'label': _(u'Specifier'),
                 'slug': 'specifier'},
        'DET': {'color': '#000033',
                 'label': _(u'Determiner'),
                 'slug': 'determiner'},
        'PERS': {'color': '#000000',
                 'label': _(u'Personal pronoun'),
                 'slug': 'personal-pronoun'},
        'ADJ': {'color': '#00CCFF',
                'label': _(u'Adjective'),
                'slug': 'adjective'},
        'ADV': {'color': '#009900',
                'label': _(u'Adverb'),
                'slug': 'adverb'},
        'V': {'color': '#FFCC33',
              'label': _(u'Verb'),
              'slug': 'verb'},
        'NUM': {'color': '#003399',
                'label': _(u'Numeral'),
                'slug': 'numeral'},
        'PRP': {'color': '#FF6666',
                'label': _(u'Preposition'),
                'slug': 'preposition'},
        'KS': {'color': '#003300',
               'label': _(u'Subordinating conjunction'),
               'slug': 'subordinating-conjunction'},
        'KC': {'color': '#0033FF',
               'label': _(u'Coordinating conjunction'),
               'slug': 'coordinating-conjunction'},
        'IN': {'color': '#FF3366',
               'label': _(u'Interjection'),
               'slug': 'interjection'},
        'EC': {'color': '#606060',
               'label': _(u'Hyphen-separated prefix'),
               'slug': 'hyphen-separated-prefix'},
        'BL': {'color': '#808080',
               'label': _(u'Blank line'),
               'slug': 'blank-line'},
        'ES': {'color': '#A0A0A0',
               'label': _(u'End of sentence'),
               'slug': 'end-of-sentence'},
        'NW': {'color': '#C0C0C0',
               'label': _(u'Non word'),
               'slug': 'non-word'},
}

COMMON_TAGS = [u'NNP', u'NN', u'CD', u'IN', u':', u'JJ', u'DT', u',', u'NNS',
        u'CC', u"''", u'VBZ', u'VBN', u'.', u'RB', u'#', u'TO', u'VB', u'VBG',
        u'VBP', u'VBD', u'MD', u'PRP', u'WDT', u'POS', u'PRP$', u'-NONE-',
        u'JJR', u'WRB', u'NNPS', u'JJS', u'EX', u'WP', u'``', u'RP', u'RBR',
        u'RBS', u'WP$', u'$', u'LS']

TAGSET = {'en-nltk': TAGSET_EN_NLTK,
          'pt-palavras': TAGSET_PT_PALAVRAS}
